dap = require("dap")
vim.keymap.set('n', '<leader>bb', function() dap.toggle_breakpoint() end, { desc = "toggle breakpoint" })
vim.keymap.set('n', '<leader>bc', function()
  dap.continue()
  vim.cmd("DapViewOpen")
end, { desc = "continue" })
vim.keymap.set('n', '<leader>bi', function() dap.step_into() end, { desc = "step into" })
vim.keymap.set('n', '<leader>bo', function() dap.step_over() end, { desc = "step over" })
-- 'u' for 'up'
vim.keymap.set('n', '<leader>bu', function() dap.step_out() end, { desc = "step out" })
vim.keymap.set('n', '<leader>br', function() dap.repl.open() end, { desc = "open repl" })
vim.keymap.set('n', '<leader>bl', function() dap.run_last() end, { desc = "run last" })
vim.keymap.set('n', '<leader>bq', function()
  dap.terminate()
  vim.cmd("DapViewClose")
end, { desc = "quit debugging session" })

vim.keymap.set('n', '<leader>bl', function() dap.list_breakpoints() end, { desc = "list breakpoints" })
vim.keymap.set('n', '<leader>be', function() dap.set_exception_breakpoints() end, { desc = "set exception breakpoints" })
